on: [push]
name: Show secrets
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
    - run: |
        import os
        print(len(os.getenv('MY_VAR')))
      shell: python
      env:
        MY_VAR: ${{ secrets.API_KEY}}
        
