name: "Unit & Smoke Tests - mamba"
on:
#   pull_request:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:

      - name: Copy Repository Contents
        uses: actions/checkout@main   
   
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: test-example/conda-environment.yaml
          environment-name: course
          cache-env: true
          
      - run: |
          micromamba activate course
          pip install -U pytest
          pytest test-example/
